# Site wide configuration

title:            Silver Bullet
locale:           en_US
url: 


# Jekyll configuration

permalink:   /:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
  line_numbers: true


# Octopress

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: false


# Site owner
owner:
  name: Tom치코 Fejfar
  avatar: bio-photo.jpg
  bio: "Web developer"
  email: tomas.fejfar@gmail.com
  disqus-shortname:
  twitter: tomasfejfar
  facebook: tomasfejfar
  google:
    plus: 
    analytics: UA-304405-13
    verify: qE0CgxGNzBcouYgXhkQmkemF7drVRegwI1bpiB1kgm8
    ad-client:
    ad-slot:
  bing-verify:
  github: tomasfejfar
  stackoverflow: 112000/tom치코-fejfar
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", ".idea"]
