parameters:
    title: 'Tomáš Fejfar'
    locale: en_US
#    url: null
    public_url: 'https://blog.tomasfejfar.cz'
    permalink: '/:title/'
    markdown: kramdown
    highlighter: rouge
    sass:
        sass_dir: _sass
        style: compressed
    kramdown:
        input: GFM
        hard_wrap: false
        auto_ids: true
        footnote_nr: 1
        entity_output: as_char
        toc_levels: 1..6
        enable_coderay: false
        line_numbers: true
    owner:
        name: 'Tomáš Fejfar'
        avatar: 'images/bio-photo.jpg'
        bio: 'Web developer'
        email: 'tomas.fejfar@gmail.com'
        disqus-shortname: 'tomasfejfar'
        twitter: 'tomasfejfar'
        facebook: 'tomasfejfar'
        google:
            analytics: 'UA-304405-13'
            verify: 'qE0CgxGNzBcouYgXhkQmkemF7drVRegwI1bpiB1kgm8'
        github: 'tomasfejfar'
        stackoverflow: '112000/tomáš-fejfar'
